config/routes.rb
Rails.application.routes.draw do
  resources :works
  resources :frames do
    collection do
      get 'add'
    end
  end
  resources :shops

end

app/models/content.rb
class Content < ActiveRecord::Base
	belongs_to :work
end

app/models/frame.rb
class Frame < ActiveRecord::Base
	belongs_to :work

	validates :registration_number1, presence: true,length: { maximum: 4 }
	validates :registration_number2, presence: true,length: { maximum: 1 }
	validates :registration_number3, presence: true,numericality: true ,length: { maximum: 4 }
	validates :frame_number1, presence: true,length: { maximum: 4 }
	validates :frame_number2, presence: true,numericality: true,length: { maximum: 7 }

	def frame_number
		self.frame_number1 + '-' + self.frame_number2 
  end

end

app/models/shop.rb
class Shop < ActiveRecord::Base
	belongs_to :work
end

app/models/work.rb
class Work < ActiveRecord::Base
	has_many :contents
	has_one :shop
	has_one :frame
	accepts_nested_attributes_for :contents, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/frames_controller.rb
class FramesController < ApplicationController
  before_action :set_frame, only: [:show, :edit, :update, :destroy]

  # GET /frames
  # GET /frames.json
  def index
    @frames = Frame.all
  end

  # GET /frames/1
  # GET /frames/1.json
  def show
  end

  # GET /frames/new
  def new
    @frame = Frame.new
  end

  def add
    @frame = Frame.new
  end

  # GET /frames/1/edit
  def edit
  end

  # POST /frames
  # POST /frames.json
  def create
    @frame = Frame.new(frame_params)

    respond_to do |format|
      if @frame.save
        format.html { redirect_to @frame, notice: 'Frame was successfully created.' }
        format.json { render :show, status: :created, location: @frame }
      else
        format.html { render :add }
        format.json { render json: @frame.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /frames/1
  # PATCH/PUT /frames/1.json
  def update
    respond_to do |format|
      if @frame.update(frame_params)
        format.html { redirect_to @frame, notice: 'Frame was successfully updated.' }
        format.json { render :show, status: :ok, location: @frame }
      else
        format.html { render :edit }
        format.json { render json: @frame.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /frames/1
  # DELETE /frames/1.json
  def destroy
    @frame.destroy
    respond_to do |format|
      format.html { redirect_to frames_url, notice: 'Frame was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_frame
      @frame = Frame.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def frame_params
      params.require(:frame).permit(:id, :registration_number1, :registration_number2, :registration_number3, :frame_number1, :frame_number2, :created_at, :updated_at)
    end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.all
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(:id, :name, :created, :modified)
    end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: [:show, :edit, :update, :destroy]

  # GET /works
  # GET /works.json
  def index
    @works = Work.all
  end

  # GET /works/1
  # GET /works/1.json
  def show
  end

  # GET /works/new
  def new
    @work = Work.new
    @work.contents.build
  end

  # GET /works/1/edit
  def edit
  end

  # POST /works
  # POST /works.json
  def create
    @work = Work.new(work_params)

    respond_to do |format|
      if @work.save
        format.html { redirect_to @work, notice: 'Work was successfully created.' }
        format.json { render :show, status: :created, location: @work }
      else
        format.html { render :new }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /works/1
  # PATCH/PUT /works/1.json
  def update
    respond_to do |format|
      if @work.update(work_params)
        format.html { redirect_to @work, notice: 'Work was successfully updated.' }
        format.json { render :show, status: :ok, location: @work }
      else
        format.html { render :edit }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1
  # DELETE /works/1.json
  def destroy
    @work.destroy
    respond_to do |format|
      format.html { redirect_to works_url, notice: 'Work was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work
      @work = Work.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_params
      params.require(:work).permit(:id, :shop_id, :work_date, :work_segment, :frame_id, :mileage, :created, :modified)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = ""
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields btn btn-info", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/frames_helper.rb
module FramesHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/frames/_form.html.erb
<%= form_for @frame, :html => { :class => "form-horizontal frame" } do |f| %>

    <% if @frame.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@frame.errors.count, "error") %> prohibited this frame from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @frame.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :registration_number1, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :registration_number1, :class => 'form-control' %>
    </div>
    <%= error_span(@frame[:registration_number1]) %>
  </div>
  <div class="control-group">
    <%= f.label :registration_number2, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :registration_number2, :class => 'form-control' %>
    </div>
    <%= error_span(@frame[:registration_number2]) %>
  </div>
  <div class="control-group">
    <%= f.label :registration_number3, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :registration_number3, :class => 'form-control' %>
    </div>
    <%= error_span(@frame[:registration_number3]) %>
  </div>
  <div class="control-group">
    <%= f.label :frame_number1, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :frame_number1, :class => 'form-control' %>
    </div>
    <%= error_span(@frame[:frame_number1]) %>
  </div>
  <div class="control-group">
    <%= f.label :frame_number2, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :frame_number2, :class => 'form-control' %>
    </div>
    <%= error_span(@frame[:frame_number2]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            frames_path, :class => 'btn btn-default' %>

<% end %>

app/views/frames/add.html.erb
<% provide(:title, 'Sign up') %>
<h1>新規車台登録</h1>
<%= form_for(@frame) do |f| %>
  <% if @frame.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @frame.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<section class="container form-horizontal">
    <div class="form-group form-inline">
      <label class="col-sm-2 control-label">登録番号</label>
      <div class="col-sm-10">
	      <%= f.text_field :registration_number1, :class => "form-control" %>
	      <%= f.text_field :registration_number2, :class => "form-control" %>
	      <%= f.text_field :registration_number3, :class => "form-control" %>
	    </div>
    </div>
    <div class="form-group form-inline">
      <label class="col-sm-2 control-label">車台番号</label>
	    <div class="col-sm-10">
      <%= f.text_field :frame_number1, :class => "form-control" %>
      <%= f.text_field :frame_number2, :class => "form-control" %>
	    </div>
    </div>
</section>
<div>
<%= f.submit "登録する", class: "btn btn-large btn-primary" %>
</div>
<% end %>

app/views/frames/edit.html.erb
<%- model_class = Frame -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/frames/index.html.erb
<%- model_class = Frame -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:registration_number1) %></th>
      <th><%= model_class.human_attribute_name(:registration_number2) %></th>
      <th><%= model_class.human_attribute_name(:registration_number3) %></th>
      <th><%= model_class.human_attribute_name(:frame_number1) %></th>
      <th><%= model_class.human_attribute_name(:frame_number2) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @frames.each do |frame| %>
      <tr>
        <td><%= link_to frame.id, frame_path(frame) %></td>
        <td><%= frame.registration_number1 %></td>
        <td><%= frame.registration_number2 %></td>
        <td><%= frame.registration_number3 %></td>
        <td><%= frame.frame_number1 %></td>
        <td><%= frame.frame_number2 %></td>
        <td><%=l frame.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_frame_path(frame), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      frame_path(frame),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_frame_path,
            :class => 'btn btn-primary' %>

app/views/frames/new.html.erb
<%- model_class = Frame -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/frames/show.html.erb
<%- model_class = Frame -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:registration_number1) %>:</strong></dt>
  <dd><%= @frame.registration_number1 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:registration_number2) %>:</strong></dt>
  <dd><%= @frame.registration_number2 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:registration_number3) %>:</strong></dt>
  <dd><%= @frame.registration_number3 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:frame_number1) %>:</strong></dt>
  <dd><%= @frame.frame_number1 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:frame_number2) %>:</strong></dt>
  <dd><%= @frame.frame_number2 %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              frames_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_frame_path(@frame), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              frame_path(@frame),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "BillingManage" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <a class="navbar-brand" href="/">HTN</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "請求管理", "/works"  %></li>
            <li><%= link_to "車台管理", "/frames"  %></li>
            <li><%= link_to "店舗管理", "/shops"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->
      <footer>
        <p>&copy; Company 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/shops/_form.html.erb
<%= form_for @shop, :html => { :class => "form-horizontal shop" } do |f| %>

    <% if @shop.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@shop.errors.count, "error") %> prohibited this shop from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @shop.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@shop[:name]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            shops_path, :class => 'btn btn-default' %>

<% end %>

app/views/shops/edit.html.erb
<%- model_class = Shop -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/shops/index.html.erb
<%- model_class = Shop -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @shops.each do |shop| %>
      <tr>
        <td><%= link_to shop.id, shop_path(shop) %></td>
        <td><%= shop.name %></td>
        <td><%=l shop.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_shop_path(shop), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      shop_path(shop),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_shop_path,
            :class => 'btn btn-primary' %>

app/views/shops/new.html.erb
<%- model_class = Shop -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/shops/show.html.erb
<%- model_class = Shop -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @shop.name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              shops_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_shop_path(@shop), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              shop_path(@shop),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/works/_content_fields.html.erb
    <tr class="record">
      <td><%= f.text_field :content, :class => 'form-control' %></td>
      <td><%= f.select :content_type, ["V", "O", "X", "C", "S", "L", "A", "_", "T", "D", "B", "P"], {}, :class => 'form-control' %></td>
      <td><%= f.number_field :quantity, in: 1...100, :class => 'form-control' %></td>
      <td><%= f.number_field :parts_cost, in: 0...1000000, :class => 'form-control' %></td>
      <td><%= f.number_field :man_hour, in: 0...100, :class => 'form-control' %></td>
      <td><%= f.number_field :pay, in: 0...100000000, :class => 'form-control' %></td>
      <td><%= f.hidden_field :_destroy %><%= link_to "削除", '#', class: "remove_fields btn btn-danger" %></td>
    </tr>

app/views/works/_form.html.erb
<%= form_for @work, :html => { :class => "form-horizontal work" } do |f| %>

  <% if @work.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@work.errors.count, "error") %> prohibited this work from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @work.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <h3><%= f.label :works , "header" %></h3>
  <div class="form-group">
    <%= f.label :shop_id, :class => 'control-label col-xs-2' %>
    <div class="form-inline">
      <%= f.collection_select :shop_id, Shop.all, :id, :name, {}, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :work_date, :class => 'control-label col-xs-2' %>
    <div class="form-inline">
      <%= f.date_field :work_date, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :work_segment , :class => 'control-label col-xs-2' %>
    <div class="form-inline">
      <label class="radio-inline"><%= f.radio_button :work_segment, '1'%>点検</label>
      <label class="radio-inline"><%= f.radio_button :work_segment, '2'%>修理</label>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :frame_id , :class => 'control-label col-xs-2' %>
    <div class="form-inline">
      <%= f.collection_select :frame_id, Frame.all, :id, :frame_number, {}, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :milege , :class => 'control-label col-xs-2' %>
    <div class="form-inline">
      <%= f.text_field :work_date, :class => 'form-control' %>
    </div>
  </div>

  <h3><%= f.label :contents , "detail" %></h3>
  <table class="table">
    <tr>
      <th>内容</th>
      <th>区分</th>
      <th>数量</th>
      <th>部品代</th>
      <th>工数</th>
      <th>工賃</th>
      <th>#</th>
    </tr>
    <%= f.fields_for :contents do |builder| %>
      <%= render "content_fields", f: builder %>
    <% end %>
    <tr>
    <td colspan="7"><%= link_to_add_fields "行追加", f, :contents %></td>
    </tr>
  </table>

  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            works_path, :class => 'btn btn-default' %>

<% end %>

app/views/works/edit.html.erb
<%- model_class = Work -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/works/index.html.erb
<%- model_class = Work -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:shop_id) %></th>
      <th><%= model_class.human_attribute_name(:work_date) %></th>
      <th><%= model_class.human_attribute_name(:work_segment) %></th>
      <th><%= model_class.human_attribute_name(:frame_id) %></th>
      <th><%= model_class.human_attribute_name(:mileage) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @works.each do |work| %>
      <tr>
        <td><%= link_to work.id, work_path(work) %></td>
        <td><%= work.shop_id %></td>
        <td><%= work.work_date %></td>
        <td><%= work.work_segment %></td>
        <td><%= work.frame_id %></td>
        <td><%= work.mileage %></td>
        <td><%=l work.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_work_path(work), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      work_path(work),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_work_path,
            :class => 'btn btn-primary' %>

app/views/works/new.html.erb
<%- model_class = Work -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/works/show.html.erb
<%- model_class = Work -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:shop_id) %>:</strong></dt>
  <dd><%= @work.shop_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:work_date) %>:</strong></dt>
  <dd><%= @work.work_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:work_segment) %>:</strong></dt>
  <dd><%= @work.work_segment %></dd>
  <dt><strong><%= model_class.human_attribute_name(:frame_id) %>:</strong></dt>
  <dd><%= @work.frame_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:mileage) %>:</strong></dt>
  <dd><%= @work.mileage %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              works_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_work_path(@work), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              work_path(@work),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>